#!/usr/bin/python3

from subprocess import Popen, PIPE
import xml.dom.minidom

print("<<<nvidia_smi>>>")
i = 0
nvidiaSMI = xml.dom.minidom.parseString(Popen(["nvidia-smi", "-q", "-x"], stdout=PIPE).communicate()[0])

for gpu in nvidiaSMI.getElementsByTagName('gpu'):
    id_gpu = gpu.getAttribute('id')
    gpu_utilization = int(gpu
                          .getElementsByTagName("utilization")[0]
                          .getElementsByTagName("gpu_util")[0]
                          .childNodes[0]
                          .data.split()[0])

    gpu_mem_usage = int(gpu
                        .getElementsByTagName("utilization")[0]
                        .getElementsByTagName("memory_util")[0]
                        .childNodes[0]
                        .data.split()[0])

    try:
        gpu_temperature = int(gpu
                              .getElementsByTagName("temperature")[0]
                              .getElementsByTagName("gpu_temp")[0]
                              .childNodes[0]
                              .data.split()[0])
    except ValueError:
        gpu_temperature: int = 0

    gpu_sm_clock = int(gpu
                       .getElementsByTagName("clocks")[0]
                       .getElementsByTagName("sm_clock")[0]
                       .childNodes[0]
                       .data.split()[0])

    gpu_graphics_clock = int(gpu
                             .getElementsByTagName("clocks")[0]
                             .getElementsByTagName("graphics_clock")[0]
                             .childNodes[0]
                             .data.split()[0])

    gpu_mem_clock = int(gpu
                        .getElementsByTagName("clocks")[0]
                        .getElementsByTagName("mem_clock")[0]
                        .childNodes[0]
                        .data.split()[0])

    print(f"smi nvidia gpu_utilization {gpu_utilization}")
    print(f"smi nvidia memory_used {gpu_mem_usage}")
    print(f"smi nvidia temperature {gpu_temperature}")
    print(f"smi nvidia graphics_clock {gpu_graphics_clock}")
    print(f"smi nvidia sm_clock {gpu_sm_clock}")
    print(f"smi nvidia msm_clock {gpu_mem_clock}")

    i += 1
